force-app/main/default/objects/Aeropuerto__c/Aeropuerto__c.object-meta.xml
<CustomObject>
    <description>Terreno extenso con pistas  para el aterrizaje y despegue de aeronaves que realizan vuelos de un lugar a otro . También está acondicionado para  reunir personas relacionadas con el servicio de transporte aéreo.</description>
    <label>Aeropuerto</label>
    <nameField>
        <label>Nombre de Aeropuerto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aeropuertos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Aeropuerto__c/fields/Codigo_IATA__c.field-meta.xml
<CustomField>
    <fullName>Codigo_IATA__c</fullName>
    <description>Designación para cada aeropuerto del mundo</description>
    <label>Código IATA</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Avion__c/Avion__c.object-meta.xml
<CustomObject>
    <description>Vehículo de transporte de pasajeros o carga que se moviliza de un lugar a otro por el aire.</description>
    <label>Avión</label>
    <nameField>
        <displayFormat>AV-{00000}</displayFormat>
        <label>Número de Avión</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aviones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Avion__c/fields/Numero_de_pasajeros_clase_negocios__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_pasajeros_clase_negocios__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Cantidad de asientos en clase negocio que tiene un avión</description>
    <label>Número de pasajeros clase negocios</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avion__c/fields/Numero_de_pasajeros_clase_turista__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_pasajeros_clase_turista__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Cantidad de asientos en clase turista que tiene un avión</description>
    <label>Número de pasajeros clase turista</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avion__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Varía de acuerdo al tipo de mercancía que transporta</description>
    <label>Tipo</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clima__c/Clima__c.object-meta.xml
<CustomObject>
    <description>Condición atmosférica propia de la ubicación de un aeropuerto en un intervalo de tiempo determinado.</description>
    <label>Clima</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Nombre de Clima</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Climas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Clima__c/fields/Aeropuerto__c.field-meta.xml
<CustomField>
    <fullName>Aeropuerto__c</fullName>
    <description>El clima es creado  para cada aeropuerto. Si eliminas un aeropuerto eliminas el conjunto de climas relacionados.</description>
    <label>Aeropuerto</label>
    <referenceTo>Aeropuerto__c</referenceTo>
    <relationshipLabel>Climas</relationshipLabel>
    <relationshipName>Climas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/departureAirportWeatherTest.cls
@isTest
public class departureAirportWeatherTest {
    @testSetup
    static void makeData(){
        Avion__c plane = new Avion__c(Numero_de_pasajeros_clase_negocios__c = 30, Numero_de_pasajeros_clase_turista__c = 46, Tipo__c  ='Airbus A330');
        insert plane;
        
        Aeropuerto__c airport = new Aeropuerto__c(Name = 'Airport1', Codigo_IATA__c = 'AI1', Localizacion__Latitude__s = 38.53, Localizacion__Longitude__s = -28.61);
        Aeropuerto__c airport2 = new Aeropuerto__c(Name = 'Airport2', Codigo_IATA__c = 'IA2');
        insert airport;
        insert airport2;
        
        Product2 flight = new Product2(Name = 'AE-2432', Avion__c = plane.Id, Fecha_y_hora_de_partida__c = datetime.now().addDays(1), Fecha_y_hora_estimada_de_llegada__c = (datetime.now() + 4).addHours(4),
                                 Aeropuerto_de_partida__c = airport.Id, Aeropuerto_de_llegada__c = airport2.Id, IsActive = true, Estado__c = 'En venta');
        
        insert flight;
    }
    
    @isTest
    static void testBatch(){
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('responseWeather');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json;charset=UTF-8');
        Test.setMock(HttpCalloutMock.class, mock);  
        
        Test.startTest();
      	Database.executeBatch(new departureAirportWeather()); 
        Test.stopTest();
		
        String airport = [SELECT Id From Aeropuerto__c LIMIT 1].Id;        
        List<Clima__c> weathers = [SELECT Id From Clima__c WHERE Aeropuerto__c =: airport];
        System.assertEquals(1, weathers.size());
    }
    
}