force-app/main/default/objects/Aeropuerto__c/Aeropuerto__c.object-meta.xml
<CustomObject>
    <description>Terreno extenso con pistas  para el aterrizaje y despegue de aeronaves que realizan vuelos de un lugar a otro . También está acondicionado para  reunir personas relacionadas con el servicio de transporte aéreo.</description>
    <label>Aeropuerto</label>
    <nameField>
        <label>Nombre de Aeropuerto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aeropuertos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clima__c/Clima__c.object-meta.xml
<CustomObject>
    <description>Condición atmosférica propia de la ubicación de un aeropuerto en un intervalo de tiempo determinado.</description>
    <label>Clima</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Nombre de Clima</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Climas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Clima__c/fields/Aeropuerto__c.field-meta.xml
<CustomField>
    <fullName>Aeropuerto__c</fullName>
    <description>El clima es creado  para cada aeropuerto. Si eliminas un aeropuerto eliminas el conjunto de climas relacionados.</description>
    <label>Aeropuerto</label>
    <referenceTo>Aeropuerto__c</referenceTo>
    <relationshipLabel>Climas</relationshipLabel>
    <relationshipName>Climas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Clima__c/fields/Fecha_y_hora_de_prediccion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_y_hora_de_prediccion__c</fullName>
    <description>Día, mes, año y hora en la que se hizo la predicción del clima para un aeropuerto</description>
    <label>Fecha y hora de predicción</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Clima__c/fields/Temperatura__c.field-meta.xml
<CustomField>
    <fullName>Temperatura__c</fullName>
    <description>Medición de calor o frío del aire en un aeropuerto y momento determinado</description>
    <label>Temperatura</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Clima__c/fields/Unidad__c.field-meta.xml
<CustomField>
    <fullName>Unidad__c</fullName>
    <description>Escala de medida de la temperatura</description>
    <label>Unidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Centigrados</fullName>
            </value>
            <value>
                <fullName>Fahrenheit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClimaModel.cls
public class ClimaModel {
    // Recibe el mapa de mapas con el id del aeropuerto(llegada o partida), sus respectivas latitudes y longitudes, para extraerlas y hacer una llamada rest a la api de climas y obtener la temperatura de la ciudad del aeropuerto de llegada, para insertar estos climas
    public static void insertWeatherData(Map<Integer,Map<String, String>> values){
        try{
        	List<Clima__c> weathers = new List<Clima__c>();
            String latitude;
            String longitude;
            String airportId;
            Decimal temperature;
            for(Integer i : values.keySet()){
                Map<String, String> valuesKeySet = values.get(i);
                if(valuesKeySet.containskey('latitud')){
                    latitude = valuesKeySet.get('latitud');
                }
                if(valuesKeySet.containskey('longitud')){
                    longitude = valuesKeySet.get('longitud');
                }
                if(valuesKeySet.containskey('id')){
                    airportId = valuesKeySet.get('id');
                }
                temperature = ClimaRest.getWeather(latitude, longitude);
                Clima__c weather = new Clima__c(Aeropuerto__c = airportId, Fecha_y_hora_de_prediccion__c = Datetime.now(), Unidad__c = 'Centigrados', Temperatura__c = temperature);
            	weathers.add(weather);
            }  
            insert weathers;
        }catch(exception e){
            System.debug('Debug insert weather' + e);
        }

    }

    // Obtiene todos los vuelos que parten el día actual, para conseguir la latitud y la longitud del aeropuerto de partida de cada vuelo, almacenando estos valores junto con el id del aeropuerto de partida en un mapa de mapas 
    @future(callout=true)
    public  static void departureAirports(){
        try{
            List<Product2> flights = [SELECT Id, Estado__c, Fecha_y_hora_de_partida__c, Aeropuerto_de_partida__c, Aeropuerto_de_partida__r.Localizacion__Latitude__s,  Aeropuerto_de_partida__r.Localizacion__Longitude__s FROM Product2 WHERE IsActive = True AND(Estado__c = 'En venta' OR Estado__c = 'Check in') AND Fecha_y_hora_de_partida__c != null AND(Fecha_y_hora_de_partida__c > TODAY AND Fecha_y_hora_de_partida__c <= TOMORROW)];
        	Map<Integer,Map<String, String>> finalResults = new Map<Integer,Map<String, String>>();
        	Map<String, String> arriveValues = new Map<String, String> ();
        	Integer counter = 0;
        	for(Product2 flight: flights){
            	String latitude = String.valueOf(flight.Aeropuerto_de_partida__r.Localizacion__Latitude__s);
            	String longitude = String.valueOf(flight.Aeropuerto_de_partida__r.Localizacion__Longitude__s);
            	String departureAirportId = flight.Aeropuerto_de_partida__c;
            	arriveValues.put('latitud', latitude);
            	arriveValues.put('longitud', longitude);
            	arriveValues.put('id', departureAirportId);
            	finalResults.put(counter, arriveValues);
            	arriveValues = new Map<String, String>();
            	counter +=1;
        	}
        	insertWeatherData(finalResults);
        }catch(exception e){
            System.debug('error ' + e.getMessage());
        }  
    }
    
    // Obtiene los vuelos que parten el día actual cada hora, para conseguir la latitud y la longitud del aeropuerto de llegada de cada vuelo, almacenando estos valores junto con el id del aeropuerto de llegada en un mapa de mapas
    @future(callout=true)
    public static void arriveAirports(){
        try{
            List<Product2> flights = [SELECT Id, Estado__c, Aeropuerto_de_llegada__c, Aeropuerto_de_llegada__r.Localizacion__Latitude__s,  Aeropuerto_de_llegada__r.Localizacion__Longitude__s, Fecha_y_hora_de_partida__c FROM Product2 WHERE Fecha_y_hora_de_partida__c = TODAY AND(Estado__c = 'En venta' OR Estado__c = 'Check in')];
        	Datetime runHour = Datetime.now(); 
        	Integer nowHour = runHour.hour();
       		Integer flightHour;
        	Map<Integer,Map<String, String>> finalResults = new Map<Integer,Map<String, String>>();
        	Map<String, String> arriveValues = new Map<String, String> ();
        	Integer counter = 0;
        	for(Product2 flight: flights){
            	flightHour= flight.Fecha_y_hora_de_partida__c.hour();
            	
            	if (flightHour == nowHour) {
                	String latitude = String.valueOf(flight.Aeropuerto_de_llegada__r.Localizacion__Latitude__s);
               		String longitude = String.valueOf(flight.Aeropuerto_de_llegada__r.Localizacion__Longitude__s);
                	String arriveAirportId = flight.Aeropuerto_de_llegada__c;
                	arriveValues.put('latitud', latitude);
                	arriveValues.put('longitud', longitude);
                	arriveValues.put('id', arriveAirportId);
                	finalResults.put(counter, arriveValues);
                	arriveValues = new Map<String, String>();
            	}
            	counter +=1;
        	}
        	insertWeatherData(finalResults);
        }catch(exception e){
            System.debug('error ' + e.getMessage());
        }

    }
}