force-app/main/default/objects/Aeropuerto__c/Aeropuerto__c.object-meta.xml
<CustomObject>
    <description>Terreno extenso con pistas  para el aterrizaje y despegue de aeronaves que realizan vuelos de un lugar a otro . También está acondicionado para  reunir personas relacionadas con el servicio de transporte aéreo.</description>
    <label>Aeropuerto</label>
    <nameField>
        <label>Nombre de Aeropuerto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aeropuertos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Aeropuerto__c/fields/Codigo_IATA__c.field-meta.xml
<CustomField>
    <fullName>Codigo_IATA__c</fullName>
    <description>Designación para cada aeropuerto del mundo</description>
    <label>Código IATA</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Avion__c/Avion__c.object-meta.xml
<CustomObject>
    <description>Vehículo de transporte de pasajeros o carga que se moviliza de un lugar a otro por el aire.</description>
    <label>Avión</label>
    <nameField>
        <displayFormat>AV-{00000}</displayFormat>
        <label>Número de Avión</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aviones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Avion__c/fields/Numero_de_pasajeros_clase_negocios__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_pasajeros_clase_negocios__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Cantidad de asientos en clase negocio que tiene un avión</description>
    <label>Número de pasajeros clase negocios</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avion__c/fields/Numero_de_pasajeros_clase_turista__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_pasajeros_clase_turista__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Cantidad de asientos en clase turista que tiene un avión</description>
    <label>Número de pasajeros clase turista</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avion__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Varía de acuerdo al tipo de mercancía que transporta</description>
    <label>Tipo</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Clima__c/Clima__c.object-meta.xml
<CustomObject>
    <description>Condición atmosférica propia de la ubicación de un aeropuerto en un intervalo de tiempo determinado.</description>
    <label>Clima</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Nombre de Clima</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Climas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Clima__c/fields/Aeropuerto__c.field-meta.xml
<CustomField>
    <fullName>Aeropuerto__c</fullName>
    <description>El clima es creado  para cada aeropuerto. Si eliminas un aeropuerto eliminas el conjunto de climas relacionados.</description>
    <label>Aeropuerto</label>
    <referenceTo>Aeropuerto__c</referenceTo>
    <relationshipLabel>Climas</relationshipLabel>
    <relationshipName>Climas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Schedule24HoursTest.cls
@isTest
public class Schedule24HoursTest {
    @testSetup 
    static void makeData(){
        List<Avion__c> planes = new List<Avion__c>();
        List<Aeropuerto__c> departureAirports = new List<Aeropuerto__c>();
        List<Aeropuerto__c> arriveAirports = new List<Aeropuerto__c>();
        Integer desNumber = 400;
        for(Integer i = 0; i < 200; i++ ){
            Avion__c plane = new Avion__c(Numero_de_pasajeros_clase_negocios__c = 30, Numero_de_pasajeros_clase_turista__c = 46, 
                                          Tipo__c  ='Airbus A330');
            planes.add(plane);
           	Aeropuerto__c departureAirport = new Aeropuerto__c(Name = 'Airport' + i, Codigo_IATA__c = 'AI' + i, 
                                                               Localizacion__Latitude__s = 38.53, Localizacion__Longitude__s = -28.61);
            departureAirports.add(departureAirport);
        	Aeropuerto__c arriveAirport = new Aeropuerto__c(Name = 'Airport' + (desNumber-i), Codigo_IATA__c = 'AI' + (desNumber-i));
            arriveAirports.add(arriveAirport);
        }
             
        insert planes;
        insert departureAirports;
        insert arriveAirports;

        List<Product2> flights = new List<Product2>();
        Integer counter = 0;
        for(Avion__c plane : planes){
            Product2 flight = new Product2(Name = 'AE-243' + counter, Avion__c = plane.Id, 
                                           Fecha_y_hora_de_partida__c = datetime.now().addDays(1).addHours(counter), 
                                           Aeropuerto_de_partida__c = departureAirports[counter].Id, IsActive = true, 
                                           Aeropuerto_de_llegada__c = arriveAirports[counter].Id, Estado__c = 'En venta');
            flights.add(flight);
            counter +=1;
        }
                
        insert flights;  
        
    }
    
    @isTest static void weatherSchedule(){
        Test.startTest();
        APIMimicTest.createApiData();
        String CronExp = '0 6 * * * ?';
        System.schedule('Setup Schedule', cronExp, new Schedule24Hours());
        Integer numberOfJobs = [SELECT Count() FROM crontrigger WHERE cronjobdetail.jobtype = '7'];
        System.assert(numberOfJobs >= 1);
        Test.stopTest();
    }
    
    @isTest static void departureAirportWeather(){
        APIMimicTest.createApiData();
        Test.startTest();
        ClimaModel.departureAirports();
        Test.stopTest();
        
        List<Clima__c> weathers = [SELECT Id FROM Clima__c];
        System.assert(!weathers.isEmpty());
    }
    
}