force-app/main/default/objects/Aeropuerto__c/Aeropuerto__c.object-meta.xml
<CustomObject>
    <description>Terreno extenso con pistas  para el aterrizaje y despegue de aeronaves que realizan vuelos de un lugar a otro . También está acondicionado para  reunir personas relacionadas con el servicio de transporte aéreo.</description>
    <label>Aeropuerto</label>
    <nameField>
        <label>Nombre de Aeropuerto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aeropuertos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Aeropuerto__c/fields/Codigo_IATA__c.field-meta.xml
<CustomField>
    <fullName>Codigo_IATA__c</fullName>
    <description>Designación para cada aeropuerto del mundo</description>
    <label>Código IATA</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Auxiliares_de_vuelo__c/Auxiliares_de_vuelo__c.object-meta.xml
<CustomObject>
    <description>Objeto Junction entre Contactos y Vuelos, para asignar múltiples Auxiliares de vuelo a un vuelo</description>
    <label>Auxiliar de vuelo</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Nombre de Auxiliares de vuelo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Auxiliares de vuelo</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Auxiliares_de_vuelo__c/fields/Auxiliares_de_vuelo__c.field-meta.xml
<CustomField>
    <fullName>Auxiliares_de_vuelo__c</fullName>
    <description>Auxiliares de vuelo que se asignan a un vuelo</description>
    <label>Auxiliares de vuelo</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Auxiliar de vuelo</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Auxiliares de vuelo</relationshipLabel>
    <relationshipName>Auxiliares_de_vuelo</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Auxiliares_de_vuelo__c/fields/Vuelo__c.field-meta.xml
<CustomField>
    <fullName>Vuelo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Un vuelo tiene múltiples auxiliares de vuelo</description>
    <label>Vuelo</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Auxiliares de vuelo</relationshipLabel>
    <relationshipName>Auxiliares_de_vuelo</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Avion__c/Avion__c.object-meta.xml
<CustomObject>
    <description>Vehículo de transporte de pasajeros o carga que se moviliza de un lugar a otro por el aire.</description>
    <label>Avión</label>
    <nameField>
        <displayFormat>AV-{00000}</displayFormat>
        <label>Número de Avión</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aviones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Avion__c/fields/Numero_de_pasajeros_clase_negocios__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_pasajeros_clase_negocios__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Cantidad de asientos en clase negocio que tiene un avión</description>
    <label>Número de pasajeros clase negocios</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avion__c/fields/Numero_de_pasajeros_clase_turista__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_pasajeros_clase_turista__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Cantidad de asientos en clase turista que tiene un avión</description>
    <label>Número de pasajeros clase turista</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avion__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Varía de acuerdo al tipo de mercancía que transporta</description>
    <label>Tipo</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AuxiliaresVueloTriggerHandlerTest.cls
@isTest
public class AuxiliaresVueloTriggerHandlerTest {
    @TestSetup
    static void makeData(){
        
        List<Contact> addContacts = new List<Contact>();
        for(Integer i = 0; i < 10; i++){
            Contact newContact = new Contact(FirstName = 'Contact' + i, LastName = 'Test', RecordTypeId = '0128a000000N3efAAC');
            addContacts.add(newContact);
        }
        insert addContacts;
        
   
        Avion__c plane = new Avion__c(Numero_de_pasajeros_clase_negocios__c = 30, Numero_de_pasajeros_clase_turista__c = 222, Tipo__c  ='Airbus A330');
        insert plane;
        
        Aeropuerto__c airport = new Aeropuerto__c(Name = 'Airport1', Codigo_IATA__c = 'AI1');
        Aeropuerto__c airport2 = new Aeropuerto__c(Name = 'Airport2', Codigo_IATA__c = 'IA2');
        insert airport;
        insert airport2;
        
        Product2 flight = new Product2(Name = 'AE-2432', Avion__c = plane.Id, Fecha_y_hora_de_partida__c = datetime.now()+ 4, Fecha_y_hora_estimada_de_llegada__c = (datetime.now() + 4).addHours(4),
                                 Aeropuerto_de_partida__c = airport.Id, Aeropuerto_de_llegada__c = airport2.Id, IsActive = true, Estado__c = 'En venta');
        
        insert flight;
        
        List<Auxiliares_de_vuelo__c> flightAttendants = new List<Auxiliares_de_vuelo__c>();
        for(Contact myContact: addContacts){
            Auxiliares_de_vuelo__c flightAttendant = new Auxiliares_de_vuelo__c(Vuelo__c = flight.Id, Auxiliares_de_vuelo__c = myContact.Id);
            flightAttendants.add(flightAttendant);
        }
        insert flightAttendants;
        
    }
    
    @isTest
    static void stopAllocationTest(){
        try{
            String getContact = [SELECT Id FROM Contact LIMIT 1].Id;
        	String flightId = [SELECT Id FROM Product2].Id;
        
        	Auxiliares_de_vuelo__c flightAttendant = new Auxiliares_de_vuelo__c(Vuelo__c = flightId, Auxiliares_de_vuelo__c = getContact);
        	insert flightAttendant;
        
        	List<Auxiliares_de_vuelo__c> flightAttResult = [SELECT Id from Auxiliares_de_vuelo__c];
      	
        }catch(exception e){
            System.assert(e.getMessage().contains('exception'));
        }
    }
    
    @isTest
    static void deleteFlightAttendant(){
        Auxiliares_de_vuelo__c flightAttendant = [SELECT Id FROM Auxiliares_de_vuelo__c LIMIT 1];
        delete flightAttendant;
        
        List<Auxiliares_de_vuelo__c> result = [SELECT Id FROM Auxiliares_de_vuelo__c];
        System.assertEquals(9, result.size());
    }
    
    @isTest
    static void updateFlightAttendant(){
        Contact newContact = new Contact(FirstName = 'Contact', LastName = 'Test', RecordTypeId = '0128a000000N3efAAC');
        insert newContact;
                                              
        String flightAttendant = [SELECT Id FROM Auxiliares_de_vuelo__c LIMIT 1].Id;
        Auxiliares_de_vuelo__c updFlightAttendant = new Auxiliares_de_vuelo__c(Id= flightAttendant, Auxiliares_de_vuelo__c = newContact.Id);
        update updFlightAttendant;
        
        List<Auxiliares_de_vuelo__c> result = [SELECT Id FROM Auxiliares_de_vuelo__c];
        System.assertEquals(10, result.size());
    }
    
}