force-app/main/default/objects/Aeropuerto__c/Aeropuerto__c.object-meta.xml
<CustomObject>
    <description>Terreno extenso con pistas  para el aterrizaje y despegue de aeronaves que realizan vuelos de un lugar a otro . También está acondicionado para  reunir personas relacionadas con el servicio de transporte aéreo.</description>
    <label>Aeropuerto</label>
    <nameField>
        <label>Nombre de Aeropuerto</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Aeropuertos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Clima__c/Clima__c.object-meta.xml
<CustomObject>
    <description>Condición atmosférica propia de la ubicación de un aeropuerto en un intervalo de tiempo determinado.</description>
    <label>Clima</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Nombre de Clima</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Climas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Clima__c/fields/Aeropuerto__c.field-meta.xml
<CustomField>
    <fullName>Aeropuerto__c</fullName>
    <description>El clima es creado  para cada aeropuerto. Si eliminas un aeropuerto eliminas el conjunto de climas relacionados.</description>
    <label>Aeropuerto</label>
    <referenceTo>Aeropuerto__c</referenceTo>
    <relationshipLabel>Climas</relationshipLabel>
    <relationshipName>Climas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Clima__c/fields/Fecha_y_hora_de_prediccion__c.field-meta.xml
<CustomField>
    <fullName>Fecha_y_hora_de_prediccion__c</fullName>
    <description>Día, mes, año y hora en la que se hizo la predicción del clima para un aeropuerto</description>
    <label>Fecha y hora de predicción</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Clima__c/fields/Temperatura__c.field-meta.xml
<CustomField>
    <fullName>Temperatura__c</fullName>
    <description>Medición de calor o frío del aire en un aeropuerto y momento determinado</description>
    <label>Temperatura</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Clima__c/fields/Unidad__c.field-meta.xml
<CustomField>
    <fullName>Unidad__c</fullName>
    <description>Escala de medida de la temperatura</description>
    <label>Unidad</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Centigrados</fullName>
            </value>
            <value>
                <fullName>Fahrenheit</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/departureAirportWeather.cls
public class departureAirportWeather implements Database.Batchable<sObject>, Database.AllowsCallouts{
    public Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'SELECT Id, Name, Fecha_y_hora_de_partida__c, Aeropuerto_de_partida__c, Aeropuerto_de_partida__r.Localizacion__Latitude__s,  Aeropuerto_de_partida__r.Localizacion__Longitude__s FROM Product2 WHERE Estado__c = \'En venta\' AND IsActive = True AND Fecha_y_hora_de_partida__c != null AND(Fecha_y_hora_de_partida__c > TODAY AND Fecha_y_hora_de_partida__c <= TOMORROW)';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<Product2> flights){
        Datetime nowDate = Datetime.now();
        Integer nowHour = nowDate.hour();
        Integer flightHour;
        List<Clima__c> weathers = new List<Clima__c>();
        for(Product2 flight : flights){
            flightHour= flight.Fecha_y_hora_de_partida__c.hour();
            if (flightHour == nowHour) {
                String latitude = String.valueOf(flight.Aeropuerto_de_partida__r.Localizacion__Latitude__s);
                String longitude = String.valueOf(flight.Aeropuerto_de_partida__r.Localizacion__Longitude__s);
                Decimal temperature = ClimaRest.getWeather(latitude, longitude);
                Clima__c weather = new Clima__c(Aeropuerto__c = flight.Aeropuerto_de_partida__c, Fecha_y_hora_de_prediccion__c = Datetime.now(), Unidad__c = 'Centigrados', Temperatura__c = temperature);
                weathers.add(weather);
            }

        }
        insert weathers;
        
    }

    public void finish(Database.BatchableContext bc){
        
    }

}