force-app/main/default/objects/Avion__c/Avion__c.object-meta.xml
<CustomObject>
    <description>Vehículo de transporte de pasajeros o carga que se moviliza de un lugar a otro por el aire.</description>
    <label>Avión</label>
    <nameField>
        <displayFormat>AV-{00000}</displayFormat>
        <label>Número de Avión</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Aviones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Avion__c/fields/Numero_de_pasajeros_clase_negocios__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_pasajeros_clase_negocios__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Cantidad de asientos en clase negocio que tiene un avión</description>
    <label>Número de pasajeros clase negocios</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avion__c/fields/Numero_de_pasajeros_clase_turista__c.field-meta.xml
<CustomField>
    <fullName>Numero_de_pasajeros_clase_turista__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Cantidad de asientos en clase turista que tiene un avión</description>
    <label>Número de pasajeros clase turista</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Avion__c/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <description>Varía de acuerdo al tipo de mercancía que transporta</description>
    <label>Tipo</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PreventiveMaintenanceTest.cls
@isTest
public class PreventiveMaintenanceTest {
    @TestSetup
    static void makeData(){
        Avion__c plane = new Avion__c(Numero_de_pasajeros_clase_negocios__c = 30, Numero_de_pasajeros_clase_turista__c = 46, Tipo__c  ='Airbus A330');
        insert plane;
        
        List<Product2> flights = new List<Product2>();
        for(Integer i = 0; i < 50; i++){
            flights.add(new Product2(Name = 'AE' + i, Avion__c = plane.Id, IsActive = true, Fecha_y_hora_de_partida__c = (datetime.now()).addHours(i)));
        }
        insert flights;
      
    }
    
    
    @isTest
    static void testBatch(){
        Test.startTest();
        PreventiveMaintenance batchTest = new PreventiveMaintenance();
        Id processId = Database.executeBatch(batchTest);
        Test.stopTest();
        
        List<Product2> flight = [SELECT Id FROM Product2];
        
        System.assertEquals(50, flight.size());
    }
}